export const DATA_PAGE_1 = [
    {
        id: "1",
        title: "You've Lost That Lovin' Feelin'",
        type: "Sports",
        publishedAt: "2013-01-03T18:12:52.000Z",
        stock: 190,
        price: "100.35",
        authors: [{ author: { id: "15", name: "Jennie Schumm" } }],
        averageRating: 4,
        ratings: 2,
        slug: "you-ve-lost-that-loving-feeling",
    },
    {
        id: "2",
        title: "Walk On By",
        type: "Novel",
        publishedAt: "2016-05-29T08:59:21.000Z",
        stock: 2201,
        price: "143.33",
        authors: [{ author: { id: "1", name: "Juanita Fay" } }],
        slug: "walk-on-by",
    },
    {
        id: "3",
        title: "Check On It",
        type: "Life",
        publishedAt: "2012-10-22T08:45:05.000Z",
        stock: 20,
        price: "24.13",
        authors: [{ author: { id: "18", name: "Jordan Weber" } }],
        slug: "check-on-it",
    },
    {
        id: "4",
        title: "Born to Run",
        type: "Life",
        publishedAt: "2015-03-22T04:06:45.000Z",
        stock: 7993,
        price: "186.74",
        authors: [{ author: { id: "4", name: "Randolph Purdy" } }],
        averageRating: 4.5,
        ratings: 2,
        slug: "born-to-run",
    },
    {
        id: "5",
        title: "I Can Dream",
        type: "Magazine",
        publishedAt: "2019-05-14T20:40:13.000Z",
        stock: 52,
        price: "46.26",
        authors: [{ author: { id: "17", name: "Hector Greenholt" } }],
        averageRating: 4,
        ratings: 1,
        slug: "i-can-dream",
    },
    {
        id: "6",
        title: "How Will I Know",
        type: "Education_nbsp__amp__nbsp_Reference",
        publishedAt: "2002-05-22T00:04:57.000Z",
        stock: 0,
        price: "170.66",
        authors: [{ author: { id: "18", name: "Jordan Weber" } }],
        slug: "how-will-i-know",
    },
    {
        id: "7",
        title: "Down Hearted Blues",
        type: "Humanities_nbsp__amp__nbsp_Social_nbsp_Sciences",
        publishedAt: "2002-11-18T22:30:58.000Z",
        stock: 1454,
        price: "56.08",
        authors: [{ author: { id: "4", name: "Randolph Purdy" } }],
        averageRating: 2.6667,
        ratings: 3,
        slug: "down-hearted-blues",
    },
    {
        id: "8",
        title: "If You Don't Know Me By Now",
        type: "Arts",
        publishedAt: "2011-07-19T01:19:11.000Z",
        stock: 150104,
        price: "10.22",
        authors: [{ author: { id: "11", name: "Brett Krajcik" } }],
        slug: "if-you-dont-know-me-by-now",
    },
    {
        id: "9",
        title: "This Guy's in Love With You",
        type: "Science_nbsp__amp__nbsp_Technology",
        publishedAt: "2016-01-22T11:03:45.000Z",
        stock: 1014,
        price: "163.62",
        authors: [{ author: { id: "16", name: "Chris Farrell" } }],
        slug: "this-guys-in-love-with-you",
    },
    {
        id: "10",
        title: "That's the Way Love Goes",
        type: "Comics",
        publishedAt: "2010-03-20T16:48:37.000Z",
        stock: 0,
        price: "171.34",
        authors: [{ author: { id: "5", name: "Charles Little" } }],
        slug: "thats-the-way-love-goes",
    },
    {
        id: "11",
        title: "Bad Moon Rising",
        type: "Novel",
        publishedAt: "2016-05-14T15:49:11.000Z",
        stock: 2222191,
        price: "74.94",
        authors: [{ author: { id: "20", name: "Luther Jacobi" } }],
        averageRating: 2,
        ratings: 2,
        slug: "bad-moon-rising",
    },
    {
        id: "12",
        title: "Kryptonite",
        type: "Novel",
        publishedAt: "2005-10-24T22:41:05.000Z",
        stock: 121,
        price: "93.48",
        authors: [{ author: { id: "16", name: "Chris Farrell" } }],
        averageRating: 4,
        ratings: 5,
        slug: "kryptonite",
    },
]
